### ISSUE TITLE
[feature request] Convert OAuth2Presenter to a trait

### ISSUE THREAD

**Issue by Fuco1** [lookyman/nette-oauth2-server#8]
Hi.

In our application all presenters inherit from a base class to enable passing of some `@persistent` attributes.  Unfortunately, as I understand it, nette does not allow passing them between classes without common parent.

This means we get into a kind of impossible situation because:

- while we can extend the `OAuth2Presenter` from this package it doesn't help because it does not inherit from our base presenter and therefore it will not get the persistent attribute
- we can not make it extend from our base presenter because, well, we don't control the code
- we *can* copy-paste all your code into our own class and make it inherit from the base presenter, but I think we will all agree that is incredibly stupid.

The change here would involve pulling all the code from the presenter to a trait.  By default the presenter provided by this package would just use the trait and everything will stay exactly the same for the outside users.

But in addition it would enable us to make our own class, inherit our own base presenter but use the shared code from this package as an implementation.

We should probably extract an interface from the `OAuth2Presenter` just to be sure it preserves the contract.

What do you think?  I can make a pull request if this seems like a not-completely-terrible idea.

(NB. Please also understand the application I work on is several years old and the architecture is not the best possible.  We know that.  It is also impossible to change.  Please don't tell us we are doing it wrong :D)

**Comment by lookyman** [comment]
Do you really need the auth presenter to inherit from your base one? It is designed to be standalone..

**Comment by Fuco1** [comment]
Well, we do some route magic and we need to somehow get a parameter to the login presenter when the redirect happens.  Because they do not inherit from the base class the parameter is stripped.  Also we can not configure it in the neon file because it is dynamic.

Specifically, our links are prefixed with an "account" 3rd level domain (where account is, roughly speaking, the client company name).  This is computed based on the logged-in user.

If there is some other way to get this information to be passed to our login presenter I would very much like to know, but we weren't able to come up with anything.

**Comment by lookyman** [comment]
Ok, I'll look into it. Thanks for the report!

**Comment by lookyman** [comment]
What if I add an event that gets triggered just before the redirect, that lets you modify the `RedirectConfig` so you can add the dynamic parameter value to the redirect destination?

EDIT: Sorry for the accidental close.. Derp.

**Comment by lookyman** [comment]
Check out https://github.com/lookyman/nette-oauth2-server/pull/9 and see if it solves your problem.

**Comment by Fuco1** [comment]
This seems doable, thanks.  I will try it out on monday and get back to you. Thanks!

**Comment by lookyman** [comment]
@Fuco1 any progress?
